import React from "react";
import Head from "next/head";
import styles from "./Layout.module.scss";
import Navbar from "../navbar/Navbar";

function Layout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>my-next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
      <div className={styles.main}>
        {children}
        </div>
    </div>
  );
}

export default Layout;
